### PR TITLE
Comment Line and comment block action

### LINKED ISSUE #21: Comment line by pressing cmd + /

### PR DESCRIPTION
**Pull request by dullin**
Fixes #21 .

I'm new to JetBrains plugin dev. I'm not sure how to integrate a test for the actions I added in the IDE.

### CODE REVIEW

**Comment by dullin** [comment]
While adding the comment block, I also found #27 where the comment block must be on separate lines. The current implementation will be able to remove "bad" comment blocks parses.

**Comment by kornilova203** [comment]
Thank you!

To figure out how to write tests you may clone [JetBrains/intellij-community](https://github.com/JetBrains/intellij-community) and search class `<The class I implemented>Test`. I searched for `CommenterTest` and found good example in [JsonCommenterTest](https://github.com/JetBrains/intellij-community/blob/master/json/tests/test/com/intellij/json/JsonCommenterTest.java).

The `JsonCommenterTest` class extends `JsonTestCase` but in our case it should directly extend `LightCodeInsightFixtureTestCase`.
Data for the tests is located in `testData` dir beside tests source root (in our case it's `resources` dir), the path to test data is determined by `getBasePath` method.

Will you add tests to the pr?

**Comment by dullin** [comment]
I'll take a look at it and add a test. Thanks for showing me where to look!

**Comment by dullin** [comment]
I added tests but found an error in the way to block comments are added.

The block comments are added at the beginning and end of the selection when they should always be added at the first column of the selected line. The line comments work correctly though.

This test file would indicate the problem:
```
x = 10;

if x ><selection> 10
    fprintf("Ok!")
e</selection>nd

disp(x)
```

I tried digging around to find if there was a way to fix this behaviour but I failed.

I found that in the code style, there's supposed to be a setting which I think is set to `true` by default.

https://github.com/JetBrains/intellij-community/blob/5663e0bde810cac18b85caffdde0daeb5bee73e4/platform/lang-api/src/com/intellij/psi/codeStyle/CommonCodeStyleSettings.java#L230-L238

I'm not sure if that's where we're supposed to look for that behavior.

**Comment by kornilova203** [comment]
hm... that's true, I did not think about it
I tried to toggle `Block comment at first column` for Java code and I did not notice any difference in how block comments are added. I'll ask my сolleagues what we can do about it

**Comment by kornilova203** [comment]
I found out that there is `SelfManagingCommenter` that receives instance of `Document` and selection offsets, so we can implement our own logic of commenting.
If you do not want to spend too much time on it then it makes sense to leave it now as it is (just do not write tests that fail) and create issue for this specific case

**Comment by dullin** [comment]
I think we can create an issue while I look into (I'll create it once the this code is merged in). The current tests do not have this issue showing.

**Comment by kornilova203** [comment]
Okay!

I found out that `BLOCK_COMMENT_AT_FIRST_COLUMN` makes difference when you select a **whole** line or multiple lines. So it's not relevant
Example from Java:
```xml
<selection>    int a;
</selection>
```
```java
/*
    int a;
*/
```
```java
    /*
    int a;
    */
```

**Comment by kornilova203** [comment]
❤️

**Pull request merged**
